name: CI

on:
  push:
    branches:
      - master
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: setup-deno
        uses: denolib/setup-deno@v2.1.0

      - name: test
        run: deno test -A --config tsconfig.json --unstable
