name: CI

on:
  push:
    branches:
      - master
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: denolib/setup-deno@v2.1.0
      - run: mkdir -p dist

      - name: build
        run: deno bundle --config tsconfig.json --importmap importmap.json --unstable mod.ts dist/wom.js
