name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
      - uses: actions/checkout@v2

      - name: test
        uses: denolib/setup-deno@v2.1.0
        run: deno test -A --config tsconfig.json --unstable
