name: release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    name: create-release
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      - uses: denolib/setup-deno@v2.1.0

      - run: mkdir -p dist

      - name: bundle-release
        run: deno bundle --config tsconfig.json --importmap importmap.json --unstable mod.ts dist/wom.js

      - name: create-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          draft: false
          prerelease: false
          release_name: Release ${{ github.ref }}
          tag_name: ${{ github.ref }}
